version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama-network
    restart: unless-stopped
volumes:
  ollama_data:
networks:
  ollama-network:
    driver: bridge
